version: '3.8'

services:
  vault_unit:
    build: .
    container_name: vault_service
    restart: always
    privileged: true 
    network_mode: host 
    
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/media3:/dev/media3" e
      - "/dev/vchiq:/dev/vchiq"     
      - "/dev/dma_heap:/dev/dma_heap" 
      
    volumes:
      - /dev:/dev 
      
    environment:
      - UNIT_ID=${UNIT_ID}
      - SERVER_IP=100.97.37.123 
      - SERVER_URL=https://27carslivestream.co.uk 
